# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  hevysync:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage\\HevySync"
      dockerfile: "./Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/HevySync.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "hevysync:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage\\HevySync:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage:/src:rw"
    - "C:\\Users\\Administrator\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2025.1.4\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_11_09_10_40_05:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
